FROM sshd:dockerfile
MAINTAINER ZJ (ZJOK2019@outlook.com)
ENV DEBIAN_FRONTEND noninteractive   		#非交互式操作
RUN apt-get -yq install apache2 && \
    rm -rf /var/lib/apt/lists/*
RUN echo "Asia/Shanghai" > /etc/timezone
ADD run.sh /run.sh
RUN chmod 755 /*.sh
RUN mkdir -p /var/lock/apache2 && mkdir -p /app && mkdir -p /var/run/apache2 && rm -rf /var/www/html && ln -s /app /var/www/html
COPY sample/ /app
ENV APACHE_RUN_USER www-data 
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid
ENV APACHE_RUN_DIR /var/run/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE SERVERADMIN admin@localhost
ENV APACHE SERVERNAME localhost
ENV APACHE SERVERALIAS docker.localhost
ENV APACHE DOCUMENTROOT /var/www
EXPOSE 80
WORKDIR /app
CMD ["/run.sh"]
